# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://reykjavik3.github.io/
date_format: "ordinal"
title: 顾南
subtitle: "公众号：丛先生dn"
description: "李丛荣的个人博客，公众号：丛先生dn"
keywords: 顾南, 丛先生dn
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: reykjavik3/reykjavik3.github.io

# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]

# ---------------- #
#      Author      #
# ---------------- #
author: licongrong
organization: 
organization_url: 
github_username: reykjavik2
location: Hangzhou, China
email: rekjavik@sina.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: reykjavik
    repo: reykjavik
    oauth:
        client_id: f2021a006d98dabdf97a
        client_secret: 31bff94e77bec55978378a9a0c26208a243be4b2
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: reykjavik
    repo: reykjavik
    clientID: f2021a006d98dabdf97a
    clientSecret: 31bff94e77bec55978378a9a0c26208a243be4b2
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
